version: "3"
services:
  opendata_api:
    build: application
    ports:
      - "8080:8080"
    volumes:
      - ./application:/go/src/application

  opendata_db_master:
    env_file: ./strage/master/.env
    build: ./strage/master
    container_name: opendata_db_master
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: opendata
      MYSQL_USER: opendata
      MYSQL_PASSWORD: opendata
    privileged: true
    networks:
      opendata_network:
        ipv4_address: 172.50.0.2

  opendata_db_slave:
    env_file: ./strage/slave/.env
    build: ./strage/slave
    container_name: opendata_db_slave
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: opendata
      MYSQL_USER: opendata
      MYSQL_PASSWORD: opendata
    depends_on:
      - opendata_db_master
    privileged: true
    networks:
      opendata_network:
        ipv4_address: 172.50.0.3

  localstack:
    image: localstack/localstack:0.11.3
    container_name: localstack
    ports:
      - 4566:4566
    environment:
      - DEFAULT_REGION=ap-northeast-1
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ~/.localstack:/tmp/localstack/

networks:
  opendata_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.50.0.0/24
